source "https://rubygems.org"

ruby '2.4.0'

gem 'activerecord'
gem 'database_rewinder'
gem 'dotenv'
gem 'faraday'
gem 'hamlit'
gem 'omniauth-twitter'
gem 'pg'
gem 'pry'
gem 'rack-flash3'
gem 'rack-test'
gem 'rake'
gem 'rspec'
gem 'sass'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'twitter'
gem 'webmock'
